banner:
  enable: true
  title: 8963æ ¸ç”µç«™
  # src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: 'white'
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# notice:
#   enable: true
#   content: Thanks for playing my game.

mode: auto
bg_image:
  enable: true
  url: /images/bright.jpg
  dark: /images/dark.jpg
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  # opacity: 0.1

social:
  - name: GitHub
    link: https://github.com/K8963
    icon: icon-github-line
    color: '#181717'

fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

medium_zoom: true

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

avatar:
  enable: true
  url: /images/avatar.jpg
  status:
    enable: true
    emoji: ğŸ˜¡
    message: æ‘†çƒ‚åˆ°åº•

menu:
  home:
    path: /
    icon: ri:home-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-line
  custom:
    title: æˆ‘
    path: /about/
    icon: ri:aliens-line

pages:

post_card:
  opacity: 0.8

post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true
  tags: true

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: åšä¸»å¾ˆæ‡’ï¼Œæ²¡æœ‰ç›®å½•
  collapse: false

reward:
  enable: false

footer:
  since: 2019
  icon:
    name: icon-cloud-line
    animated: true
    color: '#dfefef'
  powered:
    enable: false
  live_time:
    enable: false
    prefix: å‰ç«¯ç”Ÿæ¶¯å·²ç»æŒç»­äº†
    suffix: (â—'â—¡'â—)
    start_time: '2019-06-18T00:00:00'

say:
  enable: true
  api: /data/sentences.json
  hitokoto:
    enable: false

engine_search:
  enable: false

local_search:
  enable: true

cursor:
  enable: true
